# Render blueprint (monorepo) to create two services with one click:
# - backend: Python FastAPI web service (served by uvicorn)
# - frontend: Vite static site (dist)
#
# After creating services from this blueprint, update the env values as needed
# (especially `VITE_API_URL` to point to the real backend URL Render assigns).

services:
  - type: web
    name: pe-ai-backend
    rootDir: backend
    runtime: python
    # Build command: install Python deps for the backend
    buildCommand: pip install -r requirements.txt
    startCommand: uvicorn backend.main:app --host 0.0.0.0 --port $PORT
    envVars:
      - key: CORS_ALLOWED_ORIGINS
        # Example: set to the frontend URL (replace after services are created)
        value: https://pe-ai-frontend.onrender.com

  - type: static
    name: pe-ai-frontend
    rootDir: .
    # Build the frontend (root project uses Vite)
    buildCommand: npm ci && npm run build
    staticPublishPath: dist
    envVars:
      - key: VITE_API_URL
        # Replace with the backend URL Render assigns (or update after deploy)
        value: https://pe-ai-backend.onrender.com
      - key: VITE_API_BASE_URL
        # Some builds use VITE_API_BASE_URL; keep both to be safe.
        value: https://pe-ai-backend.onrender.com
